### PR TITLE
Add patch to enable building on Apple Silicon

### LINKED ISSUE #23: Apple silicon support?
It seems that there are some build errors on Apple M1 hardware:
```
==> /opt/homebrew/opt/make/bin/gmake install TARGET=x86_64-linux-musl
Last 15 lines from /Users/novuscy/Library/Logs/Homebrew/musl-cross/01.gmake:
  "_host_hooks", referenced from:
      gt_pch_save(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
      toplev::main(int, char**) in libbackend.a(toplev.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [../../src_gcc/gcc/lto/Make-lang.in:81: lto1] Error 1
gmake[3]: *** Waiting for unfinished jobs....
rm gcc.pod
gmake[3]: Leaving directory '/private/tmp/musl-cross-20201216-52153-xax24d/musl-cross-make-0.9.9/build/local/x86_64-linux-musl/obj_gcc/gcc'
gmake[2]: *** [Makefile:4361: all-gcc] Error 2
gmake[2]: Leaving directory '/private/tmp/musl-cross-20201216-52153-xax24d/musl-cross-make-0.9.9/build/local/x86_64-linux-musl/obj_gcc'
gmake[1]: *** [Makefile:222: obj_gcc/gcc/.lc_built] Error 2
gmake[1]: Leaving directory '/private/tmp/musl-cross-20201216-52153-xax24d/musl-cross-make-0.9.9/build/local/x86_64-linux-musl'
gmake: *** [Makefile:183: install] Error 2
```

### PR DESCRIPTION
**Pull request by richard-vd**
Fixes #23. See also richfelker/musl-cross-make#129.

### CODE REVIEW

**Comment by uwinx** [comment]
@richard-vd, any updates on this?

**Comment by richard-vd** [comment]
I don't have write access to this repository to merge this PR and update the bottle, but if you want it working now then I suggest to have a look at the README.md and the recent commit history in my fork: https://github.com/richard-vd/homebrew-musl-cross.

**Comment by FiloSottile** [comment]
Like @richfelker in https://github.com/richfelker/musl-cross-make/pull/129#issuecomment-895635889, I suspect the patches are right, and I believe they build a Hello World fine, but I would feel more confident pulling something with a solid justification or a backport from the GCC tree. Has upstream not fixed this yet?

**Comment by richfelker** [comment]
I doubt it breaks anything at runtime, but if it's not correct it could break building the toolchain for different hosts. That's why I'd like to see an explanation.

**Comment by uwinx** [comment]
Can confirm that using formula from this PR works for me.

**Comment by richard-vd** [comment]
Updated commit to include patch for gcc-10.3.0.

**Comment by DirectorX** [comment]
Any updates? Can I help somehow?

**Comment by FiloSottile** [comment]
Have these patches made it into upstream? If not, why? I do believe that they work when tested, but I am trying to understand why we don't have an official upstream patch to backport.

**Comment by richard-vd** [comment]
Last month this was committed to gcc master: gcc-mirror/gcc@834c8749

I will update the PR to use this patch instead.

**Comment by FiloSottile** [comment]
Awesome, thank you!

**Comment by richfelker** [comment]
Thanks! Updating the PR to use the official fix will be much appreciated, and suffices to document that it's a reasonable solution.

**Comment by FiloSottile** [comment]
@richard-vd friendly ping, do you want to import the new patch or should I go ahead with it?

**Comment by richard-vd** [comment]
I redid the Apple silicon patches for gcc-6.5.0 .. gcc-10.3.0 using commits from gcc upstream.

The URL of this patch points to today's commit in richfelker/musl-cross-make#129. I hope both PRs can be merged now.

**Comment by ismail** [comment]
@FiloSottile Friendly ping… https://github.com/richfelker/musl-cross-make/pull/129 looks like it will not be merged soon, could you merge this one?

**Comment by FiloSottile** [comment]
Ah, yes, thank you for syncing with upstream!

**Comment by ismail** [comment]
All the glory to @richard-vd , thanks for taking time to fix this!

**Pull request merged**
